version: '3'
services:
 db:
  image: postgres
 server:
   build: .
   
   ports:
    - '8000:8000'
   volumes:
    - './project:/project'
   command: "python manage.py runserver 0.0.0.0:8000"
   depends_on:
    - "db"
